--[[
    Catsaken Remastered [V3.2] 汉化脚本（完整版）
    格式：["英文原文"] = "中文翻译",
]]

local Value = {
    -- ==================== 顶部标题 ====================
    ["Catsaken Remastered [V3.2]"] = "Catsaken 重制版 [V3.2]",
    ["Configs | 15 elements"] = "配置 | 15 个元素",
    ["Audio | 23 elements"] = "音频 | 23 个元素",
    ["Miscallenous | 16 elements"] = "杂项 | 16 个元素",
    ["Antis | 12 elements"] = "防功能 | 12 个元素",
    ["Game | 20 elements"] = "游戏 | 20 个元素",
    ["Editor | 14 elements"] = "编辑器 | 14 个元素",
    ["Self | 37 elements"] = "自身 | 37 个元素",
    ["Autoblock | 38 elements"] = "自动格挡 | 38 个元素",
    ["General | 26 elements"] = "通用 | 26 个元素",
    ["Hitboxes | 9 elements"] = "命中框 | 9 个元素",
    ["Aimbot | 10 elements"] = "自瞄 | 10 个元素",
    ["Stamina | 8 elements"] = "体力 | 8 个元素",
    ["ESP | 28 elements"] = "透视 | 28 个元素",
    ["Generators | 16 elements"] = "发电机 | 16 个元素",
    ["About | 12 elements"] = "关于 | 12 个元素",

    -- ==================== 配置页 ====================
    ["Search For Configs"] = "搜索配置",
    ["Export/Import"] = "导出/导入",
    ["Export current settings to a Base64 file, then be able to load/share it for others to import and show in their configs list as specified name."] = "将当前设置导出为 Base64 文件，然后可以加载/分享给其他人导入，并在他们的配置列表中显示为指定的名称。",
    ["Name to export as"] = "导出名称",
    ["Export as Base64 and copy"] = "导出为 Base64 并复制",
    ["Enter Base64 content"] = "输入 Base64 内容",
    ["Import"] = "导入",
    ["Save Config"] = "保存配置",
    ["Delete Selected"] = "删除选中",
    ["Load Selected"] = "加载选中",
    ["Refresh List"] = "刷新列表",
    ["Share Current Settings"] = "分享当前设置",
    ["Configurations"] = "配置",
    ["Selected Config catsaken-default-loudashuai117.json"] = "已选配置 catsaken-default-loudashuai117.json",
    ["Overwrite Selected"] = "覆盖选中",
    ["Set Selected As Autoload"] = "设为自动加载",
    ["Config Name"] = "配置名称",
    ["NewConfig"] = "新配置",

    -- ==================== 音频页 ====================
    ["Lobby Music"] = "大厅音乐",
    ["Lobby music theme None"] = "大厅音乐主题 无",
    ["Custom Lobby Music ID"] = "自定义大厅音乐 ID",
    ["Custom Lobby Music File"] = "自定义大厅音乐文件",
    ["Leave empty for none"] = "留空表示无",
    ["Change Lobby Music"] = "更改大厅音乐",
    ["[Disable Lobby Music Downloads]"] = "[禁用大厅音乐下载]",
    ["Downloaded 5 lobby music files"] = "已下载 5 个大厅音乐文件",
    ["Chase Themes"] = "追逐主题",
    ["Chase Theme None"] = "追逐主题 无",
    ["Change chase theme"] = "更改追逐主题",
    ["Custom Chase ID"] = "自定义追逐 ID",
    ["Custom Chase File"] = "自定义追逐文件",
    ["Parry | ID"] = "招架 | ID",
    ["Parry | File"] = "招架 | 文件",
    ["Punch | ID"] = "出拳 | ID",
    ["Punch | File"] = "出拳 | 文件",
    ["Silence rage SFX"] = "静音狂暴音效",
    ["Change LMS"] = "更改 LMS",
    ["[Disable LMS Downloads]"] = "[禁用 LMS 下载]",
    ["Guest 1337"] = "Guest 1337",
    ["Block Success | ID"] = "格挡成功 | ID",
    ["Block Success | File"] = "格挡成功 | 文件",
    ["Last Man Standing"] = "最后幸存者",
    ["Downloaded 29 LMS files"] = "已下载 29 个 LMS 文件",
    ["LMS theme None"] = "LMS 主题 无",
    ["Custom LMS ID"] = "自定义 LMS ID",
    ["Custom LMS File"] = "自定义 LMS 文件",

    -- ==================== 杂项页 ====================
    ["Round Timer"] = "回合计时器",
    ["Round timer X 50%"] = "回合计时器 X 50%",
    ["Round timer Y 0%"] = "回合计时器 Y 0%",
    ["Only show time"] = "仅显示时间",
    ["Hide status"] = "隐藏状态",
    ["Change block animation"] = "更改格挡动画",
    ["Fake die"] = "假死",
    ["Ragdoll button (NOT FE)"] = "布娃娃按钮 (非 FE)",
    ["Blatant mode is not enabled, risky features are locked"] = "暴力模式未启用，风险功能已锁定",
    ["Blatant Mode"] = "暴力模式",
    ["Fake block"] = "假格挡",
    ["Fake block (animation)"] = "假格挡（动画）",
    ["Block animation Normal"] = "格挡动画 正常",
    ["Topbar mode Icon + Name"] = "顶栏模式 图标 + 名称",
    ["Icon + Name"] = "图标 + 名称",
    ["Icon"] = "图标",
    ["Name only"] = "仅名称",
    ["Notifications position Bottom"] = "通知位置 底部",
    ["Bottom"] = "底部",
    ["Top"] = "顶部",
    ["GUI"] = "界面",
    ["Unload"] = "卸载",
    ["Reload"] = "重载",
    ["Old GUI"] = "旧界面",
    ["Clear all notifications"] = "清除所有通知",

    -- ==================== 防功能页 ====================
    ["Anti footstep"] = "防脚步",
    ["Antis misc"] = "防杂项",
    ["Anti clone 007n7"] = "防 007n7 克隆",
    ["Antis Settings"] = "防功能设置",
    ["Notify on block"] = "格挡时通知",
    ["Anti nausea"] = "防眩晕",
    ["Anti stun"] = "防眩晕",
    ["Blatant mode is required -->"] = "需要暴力模式 -->",
    ["Anti hallucinate"] = "防幻觉",
    ["Anti fall slowness"] = "防坠落减速",
    ["Anti affects"] = "防效果",
    ["Anti slowness"] = "防减速",
    ["Anti subspace"] = "防子空间",
    ["Anti blindness"] = "防致盲",
    ["Anti glitched"] = "防故障",
    ["Anti slatekin slow/fov"] = "防 Slatekin 减速/视野",

    -- ==================== 游戏页 ====================
    ["Survivors"] = "幸存者",
    ["Survivors: 0"] = "幸存者: 0",
    ["Teleport To Random Survivor"] = "传送到随机幸存者",
    ["Emotes"] = "表情",
    ["Select emote #Too Excited"] = "选择表情 #太兴奋了",
    ["Fake emote start/stop (NO vfx, NO sfx)"] = "假表情开始/停止（无特效，无音效）",
    ["Killer: None"] = "杀手: 无",
    ["Spectate killer"] = "观战杀手",
    ["Teleport to killer"] = "传送到杀手",
    ["Farm survivors"] = "农场幸存者",
    ["Bypass killer walls"] = "绕过杀手墙壁",
    ["Grab bloxy cola"] = "拿取 Bloxy 可乐",
    ["Bring items"] = "带来物品",
    ["Auto pickup all items"] = "自动拾取所有物品",
    ["Auto pickup near items"] = "自动拾取附近物品",
    ["Killer"] = "杀手",
    ["Currency"] = "货币",
    ["Autofarm gingerbread [DISABLED]"] = "自动农场姜饼 [已禁用]",
    ["Autofarm sukkars [DISABLED]"] = "自动农场 Sukkar [已禁用]",
    ["Items"] = "物品",
    ["Grab medkit"] = "拿取医疗包",
    ["Map"] = "地图",
    ["Spike noclip"] = "尖刺穿墙",
    ["Loop Random TP all players"] = "循环随机传送所有玩家",
    ["The TP ALL effect usually only takes 10 seconds if not instant, but it can take longer"] = "TP ALL 效果通常如果不是瞬间的话只需要 10 秒，但可能会更长",
    ["Fullbright"] = "全亮",

    -- ==================== 编辑器页 ====================
    ["Set auto-load"] = "设置自动加载",
    ["Remove current auto-load"] = "移除当前自动加载",
    ["Values"] = "数值",
    ["D = Default"] = "D = 默认",
    ["Sixer:"] = "Sixer:",
    ["PursuitMaxSpeed: 17 (D=17)"] = "PursuitMaxSpeed: 17 (D=17)",
    ["PursuitLength: 0.8 (D=0.8)"] = "PursuitLength: 0.8 (D=0.8)",
    ["PursuitBaseSpeed: 7 (D=7)"] = "PursuitBaseSpeed: 7 (D=7)",
    ["Save name"] = "保存名称",
    ["Enter a name"] = "输入名称",
    ["Save"] = "保存",
    ["Refresh saves"] = "刷新存档",
    ["Reset all values"] = "重置所有数值",
    ["Saves"] = "存档",
    ["Load save no options"] = "加载存档 无选项",
    ["Load selected"] = "加载选中",
    ["Delete selected"] = "删除选中",
    ["Select key no options"] = "选择键 无选项",
    ["Select value"] = "选择数值",
    ["Value"] = "数值",
    ["Editor"] = "编辑器",
    ["Select character Sixer"] = "选择角色 Sixer",
    ["Update key to value"] = "更新键为数值",

    -- ==================== 自身页 ====================
    ["Face check"] = "朝向检查",
    ["Radius 10"] = "半径 10",
    ["Desync"] = "延迟同步",
    ["Desync button"] = "延迟同步按钮",
    ["Auto backstab"] = "自动背刺",
    ["Enable invisibility after stab"] = "背刺后启用隐身",
    ["Auto M1"] = "自动 M1",
    ["Auto Slash/M1"] = "自动斩击/M1",
    ["Godmode + Invis"] = "无敌 + 隐身",
    ["Godmode + Invisibility"] = "无敌 + 隐身",
    ["Toggle button"] = "切换按钮",
    ["Anti hit"] = "防击中",
    ["Anti hit uses Invisibility to dodge basic attacks"] = "防击中利用隐身躲避普通攻击",
    ["Stun spy"] = "眩晕间谍",
    ["Reveal ability trajectory"] = "显示技能轨迹",
    ["Walk over digital footprint"] = "走过数字脚印",
    ["Walk over trails"] = "走过轨迹",
    ["Walk over nos puddles"] = "走过 Nos 水坑",
    ["Anti block"] = "防格挡",
    ["TP Dagger"] = "传送匕首",
    ["TP Slash"] = "传送斩击",
    ["TP One Shot"] = "传送一击",
    ["Auto chicken"] = "自动小鸡",
    ["Health limit 40"] = "生命限制 40",
    ["Only when far from killer"] = "仅当远离杀手时",
    ["Veeronica control"] = "Veeronica 控制",
    ["Nosferatu auto reel"] = "Nosferatu 自动收线",
    ["Auto flip coin"] = "自动翻转硬币",
    ["Max charges 1"] = "最大充能 1",
    ["Auto Disarm Minigame"] = "自动拆除小游戏",
    ["No slowdown"] = "无减速",
    ["No slowdown from abilitys"] = "无技能减速",
    ["Device Spoofer Mobile"] = "设备欺骗 移动端",
    ["Player abilitys"] = "玩家技能",
    ["Veeronica auto trick"] = "Veeronica 自动特技",
    ["Player related settings"] = "玩家相关设置",
    ["Auto remove popups"] = "自动移除弹窗",
    ["Auto escape nosferatu"] = "自动逃离 Nosferatu",
    ["Auto unsprint"] = "自动取消冲刺",
    ["Always enable sprint"] = "始终启用冲刺",
    ["No sprint tweeting"] = "无冲刺 Tweeting",

    -- ==================== 自动格挡页 ====================
    ["Block entanglement"] = "格挡纠缠",
    ["Block void rush"] = "格挡虚空冲刺",
    ["Block walkspeed override"] = "格挡行走速度覆盖",
    ["Block corrupt nature"] = "格挡腐蚀自然",
    ["Enable sprint after block"] = "格挡后启用冲刺",
    ["Notifications"] = "通知",
    ["Block Settings"] = "格挡设置",
    ["Guest 1337 can not parry heavy attacks like mass infection, void rush, etc anymore. he only negates damage, so if you want to spare your block for an actual parry, just turn all these off"] = "Guest 1337 无法再招架重攻击，如大规模感染、虚空冲刺等。他只会抵消伤害，所以如果你想保留格挡用于真正的招架，就把这些全部关掉",
    ["HDT right size 5"] = "HDT 右侧大小 5",
    ["HDT front size 10"] = "HDT 前方大小 10",
    ["HDT back size 5"] = "HDT 后方大小 5",
    ["HDT Color (In hitbox)"] = "HDT 颜色（命中框内）",
    ["HDT Color (Not in hitbox)"] = "HDT 颜色（不在命中框内）",
    ["Color (In hitbox)"] = "颜色（命中框内）",
    ["Color (Not in hitbox)"] = "颜色（不在命中框内）",
    ["Show HDT hitbox"] = "显示 HDT 命中框",
    ["HDT left size 5"] = "HDT 左侧大小 5",
    ["Left size 5"] = "左侧大小 5",
    ["Right size 5"] = "右侧大小 5",
    ["Front size 17"] = "前方大小 17",
    ["Back size 5"] = "后方大小 5",
    ["Extra front size when walking 0"] = "行走时额外前方大小 0",
    ["Query based detection"] = "基于查询的检测",
    ["Hitbox/Visualizer"] = "命中框/可视化",
    ["Your hitbox settings determine how good auto block will be. Experiment with sizes, see what works best. The default settings are not good ones to keep."] = "你的命中框设置决定自动格挡的效果。尝试不同大小，看看哪种效果最好。默认设置不是好的选择。",
    ["Show hitbox"] = "显示命中框",
    ["Always show"] = "始终显示",
    ["Detection range and face check apply to auto raging pace/404 error/clone, not auto block"] = "检测范围和朝向检查适用于自动 Raging Pace/404 错误/克隆，而不是自动格挡",
    ["Detection range 10"] = "检测范围 10",
    ["Wait delay before blocking 0ms"] = "格挡前等待延迟 0ms",
    ["Sound detection"] = "声音检测",
    ["Your ping is 0.054s (Good)"] = "你的延迟是 0.054 秒（良好）",
    ["catsaken can only do so much to make autoblock function good on low fps/high ping , if you arent getting good blocks then check your settings, ping, and fps."] = "Catsaken 只能在低帧率/高延迟的情况下做到这些来让自动格挡功能正常，如果你没有得到好的格挡，请检查你的设置、延迟和帧率。",
    ["Settings"] = "设置",
    ["Auto punch"] = "自动出拳",
    ["Anti-bait"] = "防诱饵",
    ["Hitbox drag tech"] = "命中框拖拽技术",
    ["Auto Block"] = "自动格挡",
    ["Auto block"] = "自动格挡",
    ["Auto clone 007n7"] = "自动克隆 007n7",
    ["Auto raging pace"] = "自动 Raging Pace",
    ["Auto 404 Error"] = "自动 404 错误",
    ["Your ping is 0.051s (Good)"] = "你的延迟是 0.051 秒（良好）",

    -- ==================== 通用页 ====================
    ["Guest noclip"] = "Guest 穿墙",
    ["Infinite nos flying"] = "无限 Nos 飞行",
    ["c00lkidd WS O.R pilot"] = "c00lkidd WS O.R 驾驶",
    ["c00lkidd WS O.R noclip"] = "c00lkidd WS O.R 穿墙",
    ["Jane doe instant charge"] = "Jane Doe 瞬间充能",
    ["007n7 clone follow"] = "007n7 克隆跟随",
    ["Void rush control"] = "虚空冲刺控制",
    ["Guest anti-crash"] = "Guest 防崩溃",
    ["Guest turn control"] = "Guest 转向控制",
    ["Guest pilot"] = "Guest 驾驶",
    ["Modifiers"] = "修改器",
    ["Kick warning for all noclip features!, if you get stuck you will probably get kicked"] = "所有穿墙功能的踢出警告！如果你卡住了，你可能会被踢出",
    ["Demonic pursuit noclip"] = "恶魔追击穿墙",
    ["Demonic pursuit anti-crash"] = "恶魔追击防崩溃",
    ["Void rush noclip"] = "虚空冲刺穿墙",
    ["Void rush anti-crash"] = "虚空冲刺防崩溃",
    ["Percent 70%"] = "百分比 70%",
    ["Auto back to lobby"] = "自动返回大厅",
    ["Always show sidebar"] = "始终显示侧边栏",
    ["Always show chat"] = "始终显示聊天",
    ["Infinite disarm attempts"] = "无限拆除尝试",
    ["Privacy bypass"] = "隐私绕过",
    ["Features"] = "功能",
    ["Disable directional speed"] = "禁用方向速度",
    ["Disable directional movement"] = "禁用方向移动",
    ["Anti dusekkar protection break"] = "防 Dusekkar 保护破坏",
    ["Use dusekkaar protection through walls"] = "穿墙使用 Dusekkar 保护",
    ["Speed boost"] = "速度提升",

    -- ==================== 命中框页 ====================
    ["Hitbox Expander"] = "命中框扩展器",
    ["Enable hitbox expander"] = "启用命中框扩展器",
    ["Range 60"] = "范围 60",
    ["Hitbox Visualiser (PERFORMANCE INTENSIVE)"] = "命中框可视化（性能消耗大）",
    ["To show hitboxes, enable from ingame settings"] = "要显示命中框，请从游戏内设置中启用",
    ["The higher the transparency is, the less visible it is"] = "透明度越高，越不可见",
    ["Enable visualiser modifications"] = "启用可视化修改",
    ["Material Plastic"] = "材质 塑料",
    ["Hitbox color"] = "命中框颜色",
    ["Hitbox color (Hit)"] = "命中框颜色（击中）",
    ["Hitbox transparency 1"] = "命中框透明度 1",
    ["Hitbox transparency (Hit) 1"] = "命中框透明度（击中）1",

    -- ==================== 自瞄页 ====================
    ["M1 assist"] = "M1 辅助",
    ["Chance 360 no-scope"] = "概率 360 无镜",
    ["Void Rush range 60"] = "虚空冲刺范围 60",
    ["Walkspeed Override range 50"] = "行走速度覆盖范围 50",
    ["Charge range 14"] = "充能范围 14",
    ["Enable aimbots"] = "启用自瞄",
    ["Ability to use aimbot no options"] = "使用自瞄技能 无选项",
    ["Silent Aim allows you to hit your target without aiming"] = "静默自瞄允许你在不瞄准的情况下击中目标",
    ["Enable silent aim"] = "启用静默自瞄",
    ["Ability to use silent aim no options"] = "使用静默自瞄技能 无选项",
    ["Dusekkar target survivor"] = "Dusekkar 目标幸存者",
    ["Aimbot"] = "自瞄",

    -- ==================== 体力页 ====================
    ["Enable stamina settings ^"] = "启用体力设置 ^",
    ["Sprinting"] = "冲刺",
    ["Fast sprint (kick warning)"] = "快速冲刺（踢出警告）",
    ["Speed 26"] = "速度 26",
    ["Instant stamina recovery"] = "瞬间体力恢复",
    ["Stamina Gain"] = "体力恢复",
    ["20"] = "20",
    ["Infinite Stamina"] = "无限体力",
    ["Stamina settings arent compatible with inf stamina."] = "体力设置与无限体力不兼容。",
    ["Max Stamina"] = "最大体力",
    ["100"] = "100",
    ["Stamina Loss"] = "体力消耗",
    ["10"] = "10",

    -- ==================== 透视页 ====================
    ["Builderman Color"] = "Builderman 颜色",
    ["John Doe Color"] = "John Doe 颜色",
    ["Veeronica Color"] = "Veeronica 颜色",
    ["Azure Color"] = "Azure 颜色",
    ["Quest Color"] = "任务颜色",
    ["Gingerbread Color"] = "姜饼颜色",
    ["Zombie/Minion Color"] = "僵尸/小兵颜色",
    ["Taph Color"] = "Taph 颜色",
    ["Esp Colors"] = "透视颜色",
    ["Generator Color"] = "发电机颜色",
    ["Killer Color"] = "杀手颜色",
    ["Survivor Color"] = "幸存者颜色",
    ["Item Color"] = "物品颜色",
    ["John Doe Esp"] = "John Doe 透视",
    ["Veeronica Esp"] = "Veeronica 透视",
    ["Azure Esp"] = "Azure 透视",
    ["Bulb/Vine Ranges"] = "灯泡/藤蔓范围",
    ["Jane Doe Quest ESP"] = "Jane Doe 任务透视",
    ["Item Esp"] = "物品透视",
    ["Gingerbread Esp [DISABLED]"] = "姜饼透视 [已禁用]",
    ["Sukkar Esp [DISABLED]"] = "Sukkar 透视 [已禁用]",
    ["Zombie/Minion Esp"] = "僵尸/小兵透视",
    ["Taph Esp"] = "Taph 透视",
    ["Builderman Esp"] = "Builderman 透视",
    ["Esp"] = "透视",
    ["Outlines only"] = "仅轮廓",
    ["No outlines"] = "无轮廓",
    ["Generator Esp"] = "发电机透视",
    ["Killer Esp"] = "杀手透视",
    ["Survivor Esp"] = "幸存者透视",

    -- ==================== 发电机页 ====================
    ["Select generator 1"] = "选择发电机 1",
    ["Teleport to generator"] = "传送到发电机",
    ["Generator Settings"] = "发电机设置",
    ["Puzzle Speed 0.08s"] = "拼图速度 0.08 秒",
    ["Use legit delay when players are nearby"] = "当玩家在附近时使用合法延迟",
    ["(Legit) Puzzle Speed 0.08s"] = "(合法) 拼图速度 0.08 秒",
    ["Desync when autofarming"] = "自动农场时延迟同步",
    ["Grid size changer"] = "网格大小修改器",
    ["Grid Size 7 cols and rows"] = "网格大小 7 列和行",
    ["Complete current generator"] = "完成当前发电机",
    ["Complete every generator"] = "完成所有发电机",
    ["Teleports"] = "传送",
    ["Generators"] = "发电机",
    ["Autofarm generators"] = "自动农场发电机",
    ["Hide puzzle ui"] = "隐藏拼图界面",
    ["Auto complete generators"] = "自动完成发电机",
    ["Generator helper"] = "发电机助手",
    ["Instantly enter generator"] = "瞬间进入发电机",

    -- ==================== 关于页 ====================
    ["Created 2 weeks 4 days 9 hours ago"] = "创建于 2 周 4 天 9 小时前",
    ["169 members, 24 online"] = "169 名成员，24 人在线",
    ["Copy invite"] = "复制邀请",
    ["Your Message"] = "你的消息",
    ["Empty"] = "空",
    ["SEND IT"] = "发送",

    -- ==================== 通用文本 ====================
    ["ON"] = "开",
    ["OFF"] = "关",
    ["None"] = "无",
    ["Normal"] = "正常",
    ["Text"] = "文字",
    ["Number/Text"] = "数字/文字",
}

-- 拦截 Text 属性，自动替换为中文
local mt = getrawmetatable(game)
local old = mt.__newindex
setreadonly(mt, false)
mt.__newindex = newcclosure(function(tt, kk, v)
    if kk == "Text" and (tt:IsA("TextLabel") or tt:IsA("TextButton") or tt:IsA("TextBox")) then
        if type(v) == "string" then
            v = Value[v] or v
        end
    end
    return old(tt, kk, v)
end)
setreadonly(mt, true)

-- 提示通知
game:GetService("StarterGui"):SetCore("SendNotification", {
    Title = "Catsaken 汉化已加载",
    Text = "翻译功能已生效",
    Duration = 5,
})

-- 加载 Catsaken 脚本
loadstring(game:HttpGet("https://raw.githubusercontent.com/aibabylaugh/catsaken-real-script-not-assets/refs/heads/main/obfuscated-1448974601077002340.lua"))()