--[[
    Fart Hub 汉化脚本（完整版）
    格式：["英文原文"] = "中文翻译",
]]

local Value = {
    -- ==================== 顶部/通用 ====================
    ["Fart Hub"] = "Fart 中心",
    ["Toggle"] = "开关",
    ["Search"] = "搜索",
    ["Forsaken | Version :: 0215"] = "Forsaken | 版本 :: 0215",

    -- ==================== 左侧选项卡 ====================
    ["Home"] = "主页",
    ["Visuals"] = "视觉",
    ["Generators"] = "发电机",
    ["玩家"] = "玩家",
    ["杂项"] = "杂项",
    ["Rage"] = "狂暴",
    ["Aiming"] = "自瞄",
    ["Block"] = "格挡",
    ["Music"] = "音乐",
    ["Addons"] = "插件",
    ["Animations"] = "动画",
    ["UI Settings"] = "界面设置",

    -- ==================== 主页/信息 ====================
    ["Profile"] = "个人资料",
    ["Information"] = "信息",
    ["Welcome to FartHub, Have fun!"] = "欢迎来到 FartHub，玩得开心！",
    ["Script is updated"] = "脚本已更新",
    ["Developers"] = "开发者",
    ["[ivannetta] - Owner"] = "[ivannetta] - 所有者",
    ["Contributors"] = "贡献者",
    ["[union] - Created autoblock and others."] = "[union] - 创建了自动格挡和其他功能。",
    ["[io] - Improved the script"] = "[io] - 改进了脚本",
    ["[Dottik] - Helper with Generators"] = "[Dottik] - 发电机助手",
    ["[lopticat] - Lopticat has been the main artist for almost everything in the script."] = "[lopticat] - Lopticat 是脚本中几乎所有内容的主要美术。",
    ["[upio] - Helped with Optimization"] = "[upio] - 帮助优化",
    ["[Mstudio45] - He meows in vc for motivation"] = "[Mstudio45] - 他在语音里喵喵叫来激励大家",
    ["[who_else123] - Authored ESP & optimised the script"] = "[who_else123] - 编写了透视并优化了脚本",
    ["[dedysence] - Introduced some features to the script"] = "[dedysence] - 为脚本引入了一些功能",
    ["Good Afternoon! loudashuai117. Its just a good gaming chair yk?"] = "下午好！loudashuai117。这只是一个好的电竞椅，你知道吗？",
    ["Executor: delta"] = "执行器: delta",
    ["You used the script 0 times."] = "你已使用脚本 0 次。",
    ["Support Server"] = "支持服务器",

    -- ==================== 自瞄 ====================
    ["Aiming"] = "自瞄",
    ["It aims for you wow"] = "它为你自瞄 哇",
    ["Aimbot"] = "自瞄",
    ["设置"] = "设置",
    ["Silent Aim"] = "静默自瞄",
    ["Aimbot Prediction"] = "自瞄预测",
    ["0.15 Multiplier"] = "0.15 倍率",
    ["Aimbot Rotation Speed"] = "自瞄旋转速度",
    ["Aimbot Max Distance"] = "自瞄最大距离",
    ["50 Studs"] = "50 单位",
    ["Rotate camera"] = "旋转相机",
    ["Bezier Curve Visualizer"] = "贝塞尔曲线可视化",
    ["Curve Color"] = "曲线颜色",
    ["Aimbot Aim Events"] = "自瞄事件",
    ["Aimbot Priority"] = "自瞄优先级",
    ["Nearest"] = "最近",
    ["Closest To Cursor"] = "最接近准星",
    ["This will change how aimbot selects targets, Inside the circle or the closest to you."] = "这将改变自瞄选择目标的方式，圆圈内或离你最近的。",
    ["Silent Aim Prediction Strength"] = "静默自瞄预测强度",
    ["Dusekkar Aim Target"] = "Dusekkar 自瞄目标",
    ["Killer"] = "杀手",
    ["Target Swap"] = "目标切换",
    ["Unknown"] = "未知",
    ["JaneDoe Aim Target"] = "JaneDoe 自瞄目标",
    ["Face Same Way"] = "面朝同一方向",
    ["Wallcheck Mode"] = "墙体检查模式",
    ["Disabled"] = "已禁用",
    ["Aimbot Characters"] = "自瞄角色",
    ["TwoTime, Guest1337, Ch..."] = "TwoTime, Guest1337, Ch...",
    ["Silent Aim Characters"] = "静默自瞄角色",
    ["Dusekkar"] = "Dusekkar",
    ["Silent Aim Part Picker, Click where u want silent aim to aim duhhhhh"] = "静默自瞄部位选择器，点击你想要静默自瞄瞄准的位置 懂？",
    ["Dusekkar Wallbang"] = "Dusekkar 穿墙",
    ["自瞄"] = "自瞄",
    ["它为你自瞄 哇"] = "它为你自瞄 哇",
    ["贝塞尔曲线可视化"] = "贝塞尔曲线可视化",
    ["曲线颜色"] = "曲线颜色",
    ["自瞄事件"] = "自瞄事件",
    ["这将改变自瞄选择目标的方式，圆圈内或离你最近的。"] = "这将改变自瞄选择目标的方式，圆圈内或离你最近的。",
    ["自瞄优先级"] = "自瞄优先级",
    ["最近"] = "最近",
    ["静默自瞄"] = "静默自瞄",
    ["静默自瞄角色"] = "静默自瞄角色",
    ["未知"] = "未知",
    ["墙体检查模式"] = "墙体检查模式",
    ["已禁用"] = "已禁用",
    ["Camera"] = "相机",
    ["Character"] = "角色",
    ["面朝同一方向"] = "面朝同一方向",

    -- ==================== 狂暴 ====================
    ["Rage"] = "狂暴",
    ["Gaming Chair"] = "电竞椅",
    ["Press Delay"] = "按下延迟",
    ["0.12 Seconds"] = "0.12 秒",
    ["No Anti-Cheat"] = "无防作弊",
    ["Anti Reach"] = "防延伸",
    ["Character Specific"] = "角色特定",
    ["Nosferatu only"] = "仅 Nosferatu",
    ["Nos Kill Closest"] = "Nos 击杀最近",
    ["Nos Loop Kill Everyone"] = "Nos 循环击杀所有人",
    ["Misc Rage Functions"] = "杂项狂暴功能",
    ["Auto Screen Popups"] = "自动屏幕弹窗",
    ["Auto Escape Nosferatu"] = "自动逃离 Nosferatu",
    ["Start Delay"] = "开始延迟",
    ["0.15 Seconds"] = "0.15 秒",
    ["Max Aim Distance"] = "最大自瞄距离",
    ["Static Reach"] = "静态延伸",
    ["10 Studs"] = "10 单位",
    ["Reach Prediction"] = "延伸预测",
    ["1 Seconds"] = "1 秒",
    ["Reach Strength"] = "延伸强度",
    ["1.2 Multiplier"] = "1.2 倍率",
    ["Reach Delay"] = "延伸延迟",
    ["Reach"] = "延伸",
    ["Reach Type"] = "延伸类型",
    ["Reach Characters"] = "延伸角色",
    ["Slasher, c00lkidd, Nol..."] = "Slasher, c00lkidd, Nol...",
    ["狂暴"] = "狂暴",
    ["电竞椅"] = "电竞椅",
    ["杂项狂暴功能"] = "杂项狂暴功能",
    ["自动屏幕弹窗"] = "自动屏幕弹窗",
    ["自动逃离 Nosferatu"] = "自动逃离 Nosferatu",
    ["开始延迟"] = "开始延迟",
    ["0.15 秒"] = "0.15 秒",
    ["按下延迟"] = "按下延迟",
    ["0.12 秒"] = "0.12 秒",
    ["无防作弊"] = "无防作弊",
    ["防延伸"] = "防延伸",
    ["延伸"] = "延伸",
    ["延伸类型"] = "延伸类型",
    ["Aim"] = "自瞄",
    ["Static"] = "静态",
    ["延伸角色"] = "延伸角色",

    -- ==================== 杂项 ====================
    ["Misc"] = "杂项",
    ["Miscellaneous functions and utilities."] = "杂项功能和实用工具。",
    ["General"] = "通用",
    ["UI"] = "界面",
    ["Visibility"] = "可见性",
    ["设备"] = "设备",
    ["Device"] = "设备",
    ["UI Timer Position"] = "界面计时器位置",
    ["TopBar Buttons"] = "顶栏按钮",
    ["Dusekkar Target"] = "Dusekkar 目标",
    ["Frontflip"] = "前空翻",
    ["假格挡"] = "假格挡",
    ["Ragdoll"] = "布娃娃",
    ["Jane Doe Target"] = "Jane Doe 目标",
    ["Spoof Device"] = "欺骗设备",
    ["Anti Features"] = "防功能",
    ["Anti Auto 404"] = "防自动 404",
    ["Anti Autoblock"] = "防自动格挡",
    ["Fake Name"] = "假名字",
    ["d6dude16"] = "d6dude16",
    ["Streamer Mode"] = "主播模式",
    ["Show Hidden Stats"] = "显示隐藏统计",
    ["Delete Killer Only Walls"] = "删除仅杀手墙壁",
    ["Jane Doe Instant Crystal Cha"] = "Jane Doe 瞬间水晶充能",
    ["Toggle Chat Visibility"] = "切换聊天可见性",
    ["杂项"] = "杂项",
    ["杂项功能和实用工具。"] = "杂项功能和实用工具。",
    ["通用"] = "通用",
    ["界面"] = "界面",
    ["可见性"] = "可见性",
    ["界面计时器位置"] = "界面计时器位置",
    ["顶栏按钮"] = "顶栏按钮",
    ["Dusekkar 目标"] = "Dusekkar 目标",
    ["前空翻"] = "前空翻",
    ["Fake Block"] = "假格挡",
    ["布娃娃"] = "布娃娃",
    ["Jane Doe 目标"] = "Jane Doe 目标",
    ["欺骗设备"] = "欺骗设备",
    ["PC"] = "PC",
    ["Mobile"] = "移动端",
    ["Console"] = "主机",
    ["防自动 404"] = "防自动 404",
    ["防自动格挡"] = "防自动格挡",
    ["切换聊天可见性"] = "切换聊天可见性",
    ["防功能"] = "防功能",

    -- ==================== 玩家 ====================
    ["玩家"] = "玩家",
    ["Player Character Functions"] = "玩家角色功能",
    ["Speed"] = "速度",
    ["Infinite Stamina"] = "无限体力",
    ["Max Stamina"] = "最大体力",
    ["Player"] = "玩家",
    ["Stamina"] = "体力",
    ["Note: Stamina changes apply after round ends"] = "注意：体力更改在回合结束后生效",
    ["无限体力"] = "无限体力",
    ["Minimum Stamina"] = "最小体力",
    ["Stamina Gain Speed"] = "体力恢复速度",
    ["最大体力"] = "最大体力",
    ["Walkspeed Multiplier"] = "行走速度倍率",
    ["1 Multiplier"] = "1 倍率",
    ["Walkspeed Type"] = "行走速度类型",
    ["Blatant"] = "暴力",
    ["Physics Rate"] = "物理速率",
    ["1x"] = "1x",
    ["Physics Rate Multiplier"] = "物理速率倍率",
    ["Disable Slowness Modifiers"] = "禁用减速修正",
    ["Actions"] = "动作",
    ["Abilities"] = "技能",
    ["Invisibility"] = "隐身",
    ["Better Noli Controls"] = "更好的 Noli 控制",
    ["Noli Steer Strength"] = "Noli 转向强度",
    ["Better Sixer Controls"] = "更好的 Sixer 控制",
    ["Sixer Steer Strength"] = "Sixer 转向强度",
    ["Better c00lkidd Controls"] = "更好的 c00lkidd 控制",
    ["c00lkidd Steer Strength"] = "c00lkidd 转向强度",
    ["Veeronica SK8 Controls"] = "Veeronica SK8 控制",

    -- ==================== 发电机 ====================
    ["Generators"] = "发电机",
    ["Auto Solve Generators and other generator stuff."] = "自动解决发电机和其他发电机相关功能。",
    ["Blatant"] = "暴力",
    ["设置"] = "设置",
    ["Generator Solve Delay"] = "发电机解决延迟",
    ["2.5 Seconds"] = "2.5 秒",
    ["Generator Delay Randomness"] = "发电机延迟随机性",
    ["0 Seconds"] = "0 秒",
    ["Realistic"] = "真实",
    ["Humanizer Solve Speed"] = "拟人化解决速度",
    ["1"] = "1",
    ["Generator Helper"] = "发电机助手",
    ["Helper Transparency"] = "助手透明度",
    ["50%"] = "50%",
    ["Generator Backgrounds"] = "发电机背景",
    ["Background Video."] = "背景视频。",
    ["Subway Surfers"] = "地铁跑酷",
    ["Video Volume"] = "视频音量",
    ["0.5"] = "0.5",
    ["Auto Solve Generator"] = "自动解决发电机",
    ["Auto Solve Generator disabled."] = "自动解决发电机已禁用。",
    ["Realistic Solver"] = "真实解决器",
    ["发电机"] = "发电机",
    ["自动解决发电机和其他发电机相关功能。"] = "自动解决发电机和其他发电机相关功能。",
    ["暴力"] = "暴力",
    ["自动解决发电机"] = "自动解决发电机",
    ["自动解决发电机已禁用。"] = "自动解决发电机已禁用。",
    ["真实"] = "真实",
    ["真实解决器"] = "真实解决器",
    ["发电机助手"] = "发电机助手",
    ["助手透明度"] = "助手透明度",
    ["发电机背景"] = "发电机背景",
    ["背景视频。"] = "背景视频。",
    ["地铁跑酷"] = "地铁跑酷",
    ["视频音量"] = "视频音量",

    -- ==================== 视觉 ====================
    ["Visuals"] = "视觉",
    ["ESP and other visuals."] = "透视和其他视觉。",
    ["Distance"] = "距离",
    ["Stamina Bar"] = "体力条",
    ["Stamina Text"] = "体力文字",
    ["2D Boxes"] = "2D 方框",
    ["3D Boxes"] = "3D 方框",
    ["Skeleton"] = "骨骼",
    ["Skeleton Transparency"] = "骨骼透明度",
    ["Outline Transparency"] = "轮廓透明度",
    ["Fill Transparency"] = "填充透明度",
    ["Text Size"] = "文字大小",
    ["1x Trails Visualizer"] = "1x 轨迹可视化",
    ["World"] = "世界",
    ["Disable Blur"] = "禁用模糊",
    ["全亮"] = "全亮",
    ["Self"] = "自身",
    ["Effects"] = "效果",
    ["Princess Mode"] = "公主模式",
    ["Field of View"] = "视野",
    ["80 deg/120 deg"] = "80 度/120 度",
    ["ESP Settings"] = "透视设置",
    ["Highlights"] = "高亮",
    ["Tracers"] = "轨迹",
    ["Tracer Start Position"] = "轨迹起始位置",
    ["Bottom"] = "底部",
    ["Offscreen Arrows"] = "屏幕外箭头",
    ["Arrow Radius"] = "箭头半径",
    ["50/150"] = "50/150",
    ["Names"] = "名字",
    ["Player ESP"] = "玩家透视",
    ["Items"] = "物品",
    ["Minions"] = "小兵",
    ["Projectile"] = "投射物",
    ["Traps"] = "陷阱",
    ["Quests"] = "任务",
    ["1x Trails Box Length"] = "1x 轨迹方框长度",
    ["25/150"] = "25/150",
    ["1x Trails Expiration"] = "1x 轨迹过期",
    ["On sound destroyed"] = "声音被销毁时",
    ["1x Trails Freeze On"] = "1x 轨迹冻结于",
    ["Never"] = "从不",
    ["Create Projectile"] = "创建投射物",
    ["Delay"] = "延迟",
    ["Azure Plant Ranges"] = "天蓝色植物范围",
    ["Azure Plants"] = "天蓝色植物",
    ["Seeker Bulbs, Vines"] = "追踪者灯泡，藤蔓",
    ["Seeker Bulbs"] = "追踪者灯泡",
    ["Vines"] = "藤蔓",
    ["Bulb Range Color"] = "灯泡范围颜色",
    ["Vine Range Color"] = "藤蔓范围颜色",
    ["Plant Ring Thickness"] = "植物环厚度",
    ["2/6"] = "2/6",
    ["Plant Ring Max Distance"] = "植物环最大距离",
    ["300/600"] = "300/600",
    ["Remove Health Glitch"] = "移除生命值故障",
    ["Delete John Doe's Footprints"] = "删除 John Doe 的脚印",
    ["Disable Subspace Effect"] = "禁用子空间效果",
    ["Disable Noli Hallucinations"] = "禁用 Noli 幻觉",
    ["视觉"] = "视觉",
    ["透视和其他视觉。"] = "透视和其他视觉。",
    ["ESP"] = "透视",
    ["玩家透视"] = "玩家透视",
    ["物品"] = "物品",
    ["小兵"] = "小兵",
    ["投射物"] = "投射物",
    ["陷阱"] = "陷阱",
    ["禁用模糊"] = "禁用模糊",
    ["Full Bright"] = "全亮",
    ["自身"] = "自身",
    ["效果"] = "效果",
    ["移除生命值故障"] = "移除生命值故障",
    ["删除 John Doe 的脚印"] = "删除 John Doe 的脚印",
    ["禁用子空间效果"] = "禁用子空间效果",
    ["Disable Noli Halucinations"] = "禁用 Noli 幻觉",

    -- ==================== 格挡 ====================
    ["格挡"] = "格挡",
    ["Automatically block incoming attacks"] = "自动格挡来袭攻击",
    ["Main"] = "主",
    ["Config"] = "配置",
    ["Hitbox"] = "命中框",
    ["Characters"] = "角色",
    ["Autoblock Delay"] = "自动格挡延迟",
    ["0.35 Negation"] = "0.35 抵消",
    ["Autoblock Sound Events"] = "自动格挡声音事件",
    ["Autoblock Characters"] = "自动格挡角色",
    ["Guest1337, 007n7, Slas..."] = "Guest1337, 007n7, Slas...",
    ["Hitbox Preview"] = "命中框预览",
    ["Hitbox Hits"] = "命中框击中次数",
    ["2"] = "2",
    ["AB Hitbox Color"] = "AB 命中框颜色",
    ["Survivor Autoblock"] = "幸存者自动格挡",
    ["Block Projectiles"] = "格挡投射物",
    ["Auto Punch"] = "自动出拳",
    ["Killer Autoblock"] = "杀手自动格挡",
    ["Ghost Block"] = "幽灵格挡",
    ["Hitbox Distance"] = "命中框距离",
    ["1 Studs"] = "1 单位",
    ["Autoblock Hitbox Multiplier"] = "自动格挡命中框倍率",
    ["1.5 times"] = "1.5 倍",
    ["Autoblock Hitbox Transparency"] = "自动格挡命中框透明度",

    -- ==================== 配置 ====================
    ["Config Upload"] = "配置上传",
    ["Note: You can only upload a config once every 12 hours."] = "注意：你每 12 小时只能上传一次配置。",
    ["Specify the type of config. Eg: [ Rage ] or [ Closet ]."] = "指定配置类型。例如：[ 狂暴 ] 或 [ 衣柜 ]。",
    ["Configs without a type tag will be denied and not uploaded."] = "没有类型标签的配置将被拒绝且不会上传。",
    ["Config Name"] = "配置名称",
    ["Upload Current Config"] = "上传当前配置",
    ["Config Downloader"] = "配置下载器",
    ["Here you can download configs shared by other users."] = "在这里你可以下载其他用户分享的配置。",
    ["Selected Config"] = "已选配置",
    ["Configs"] = "配置列表",
    ["Refresh"] = "刷新",
    ["Download Config"] = "下载配置",
    ["Set as default"] = "设为默认",
    ["Reset default"] = "重置默认",
    ["Current default theme: none"] = "当前默认主题: 无",
    ["Theme JSON"] = "主题 JSON",
    ["Import theme"] = "导入主题",
    ["Export current theme"] = "导出当前主题",
    ["Custom theme name"] = "自定义主题名称",
    ["Create theme"] = "创建主题",
    ["Custom themes"] = "自定义主题",
    ["Load theme"] = "加载主题",
    ["Overwrite theme"] = "覆盖主题",
    ["Delete theme"] = "删除主题",
    ["Load config"] = "加载配置",
    ["Overwrite config"] = "覆盖配置",
    ["Delete config"] = "删除配置",
    ["Set as autoload"] = "设为自动加载",
    ["Reset autoload"] = "重置自动加载",
    ["Current autoload config: .."] = "当前自动加载配置: ..",
    ["Config JSON"] = "配置 JSON",
    ["Import config"] = "导入配置",
    ["Export current config"] = "导出当前配置",
    ["Refresh list"] = "刷新列表",
    ["Refresh List"] = "刷新列表",

    -- ==================== UI 设置 ====================
    ["Themes"] = "主题",
    ["Utility"] = "实用工具",
    ["Background color"] = "背景颜色",
    ["Main color"] = "主颜色",
    ["Accent color"] = "强调色",
    ["Outline color"] = "轮廓颜色",
    ["Font color"] = "字体颜色",
    ["Contrast check: good (15.1:1)"] = "对比度检查: 良好 (15.1:1)",
    ["Font Face"] = "字体",
    ["Code"] = "代码",
    ["Menu keybind"] = "菜单按键",
    ["RightShift"] = "右 Shift",
    ["Discord RPC"] = "Discord RPC",
    ["Swap RPC Icons Position"] = "交换 RPC 图标位置",
    ["Unload"] = "卸载",
    ["Custom Cursor"] = "自定义光标",
    ["Debug Mode"] = "调试模式",
    ["Notification Side"] = "通知位置",
    ["Right"] = "右侧",
    ["Background Image"] = "背景图片",
    ["Theme list"] = "主题列表",
    ["Configuration"] = "配置",
    ["Config name"] = "配置名称",
    ["Create config"] = "创建配置",
    ["Config list"] = "配置列表",
    ["DPI Scale"] = "DPI 缩放",
    ["100%"] = "100%",

    -- ==================== 动画 ====================
    ["Animations"] = "动画",
    ["Stuff related to animations"] = "与动画相关的内容",
    ["Animation Selector"] = "动画选择器",
    ["Enable Custom Animations"] = "启用自定义动画",
    ["Free Emotes"] = "免费表情",
    ["Select Emotes"] = "选择表情",
    ["Enable Free Emotes"] = "启用免费表情",
    ["Custom Animation"] = "自定义动画",
    ["None"] = "无",
    ["Animation Speed"] = "动画速度",
    ["1x"] = "1x",

    -- ==================== 插件 ====================
    ["Addons"] = "插件",
    ["Addons created by the community"] = "社区创建的插件",
    ["Warning"] = "警告",
    ["Addons are only available to premium users."] = "插件仅对高级用户可用。",

    -- ==================== 音乐 ====================
    ["音乐"] = "音乐",
    ["Custom music for lobby and last man standing"] = "大厅和最后幸存者的自定义音乐",
    ["Settings"] = "设置",
    ["Custom LMS Music"] = "自定义 LMS 音乐",
    ["Sigmaboy Phonk"] = "Sigmaboy Phonk",
    ["Custom Lobby Music"] = "自定义大厅音乐",
    ["Canto3 Boss Battle"] = "Canto3 Boss 战",
    ["Custom Chase Music"] = "自定义追逐音乐",
    ["Grass Skirt"] = "草裙",
    ["Custom Ambiance Music"] = "自定义环境音乐",
    ["Custom"] = "自定义",
    ["Manage"] = "管理",
    ["Delete all sounds"] = "删除所有声音",
    ["Delete All Sounds"] = "删除所有声音",
    ["Enable Custom LMS Music"] = "启用自定义 LMS 音乐",
    ["Enable Custom Lobby Music"] = "启用自定义大厅音乐",
    ["Enable Custom Chase Music"] = "启用自定义追逐音乐",
    ["Enable Custom Ambiance Music"] = "启用自定义环境音乐",
    ["How To Get Custom Sounds:"] = "如何获取自定义声音：",
    ["1. Upload your music file to a platform like Discord or any file hosting service."] = "1. 将你的音乐文件上传到 Discord 或任何文件托管服务。",
    ["2. Get the direct download link to your file (must be a RAW file link, not a YouTube link)."] = "2. 获取文件的直接下载链接（必须是 RAW 文件链接，而不是 YouTube 链接）。",
    ["3. Enter that download link in the first text box below."] = "3. 在下面的第一个文本框中输入该下载链接。",
}

-- 拦截 Text 属性，自动替换为中文
local mt = getrawmetatable(game)
local old = mt.__newindex
setreadonly(mt, false)
mt.__newindex = newcclosure(function(tt, kk, v)
    if kk == "Text" and (tt:IsA("TextLabel") or tt:IsA("TextButton") or tt:IsA("TextBox")) then
        if type(v) == "string" then
            v = Value[v] or v
        end
    end
    return old(tt, kk, v)
end)
setreadonly(mt, true)

-- 提示通知
game:GetService("StarterGui"):SetCore("SendNotification", {
    Title = "Fart Hub 汉化已加载",
    Text = "翻译功能已生效",
    Duration = 5,
})

-- 加载 Fart Hub 脚本
loadstring(game:HttpGet("https://raw.githubusercontent.com/ivannetta/ShitScripts/refs/heads/main/".."forsaken.lua"))()